# 应用配置
application:
  server.port: 7080
  name: register-go

#  redis配置
redis:
  redisConfig:
    - {addr: 192.168.56.131:6379}
    - {addr: 192.168.56.132:6379, readOnly: true}
    - {addr: 192.168.56.132:6380, readOnly: true}
# 日志配置
logrus:
  level: trace
  logFileName: register-go
  filePath: logs/
  # 30 * 24 * 60 * 60 一个月
  maxAge: 2592000
  # 24 * 60 * 60 一天
  rotationTime: 86400

mysql:
  driverName: mysql
  ipAddr: xxx.xx.xx.xxx
  port: 3306
  username: root
  password: admin
  database: registergo
  maxOpenConn: 100
  maxIdeConn: 100
  # 7 * 24 * 60 * 60
  connMaxLifetime: 604800

# rabbitmq的配置
rabbit:
  ipAddr: 192.168.56.130
  port: 5672
  # vhost命名不要带 /, 如/hmall,这样命名会有异常
  vhost: hmall
  username: admin
  password: admin


